config/routes.rb
Rails.application.routes.draw do
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :payments, only: [:new, :create]
  resources :products, only: [:index, :show]

  # root 'payments#new'
  root 'products#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payments_controller.rb
# app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def new
      # This action will render the payment form
    end
  
    def create
      # Handle the payment request using the provided code
      require 'uri'
      require 'net/http'
      require 'openssl'
  
      url = URI("https://test.payu.in/_payment")
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
  
      request = Net::HTTP::Post.new(url)
      request["Accept"] = 'application/json'
      request["Content-Type"] = 'application/x-www-form-urlencoded'
  
      request.body = "key=JP***g&txnid=txnid62351480640&amount=10.00&firstname=Ashish&email=test@gmail.com&phone=9876543210&productinfo=iPhone&pg=TESTPG&bankcode=TESTPGNB&surl=https://test-payment-middleware.payu.in/simulatorResponse&furl=https://test-payment-middleware.payu.in/simulatorResponse&ccnum=&ccexpmon=&ccexpyr=&ccvv=&ccname=&txn_s2s_flow=4&hash=e48c5dd4fcde2afebbeac4e34347382d11c93191b8e86b6830102b81f7679b3aa020e472f2b8209d580df5ac0936f96f212e19943b7137a579acf51795dc350e"
      
      response = http.request(request)
  
      # Process the response here (redirect, show response to the user, etc.)
    end
  end
  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaymentGateway</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/new.html.erb
<!-- app/views/payments/new.html.erb -->
<%= form_tag payments_path, method: :post do %>
  <!-- Hidden Fields -->
  <%= hidden_field_tag :key, 'JP***g' %>
  <%= hidden_field_tag :txnid, 'txnid62351480640' %>
  <%= hidden_field_tag :amount, '10.00' %>
  <%= hidden_field_tag :firstname, 'Ashish' %>
  <%= hidden_field_tag :email, 'test@gmail.com' %>
  <%= hidden_field_tag :phone, '9876543210' %>
  <%= hidden_field_tag :productinfo, 'iPhone' %>
  <%= hidden_field_tag :pg, 'TESTPG' %>
  <%= hidden_field_tag :bankcode, 'TESTPGNB' %>
  <%= hidden_field_tag :surl, 'https://test-payment-middleware.payu.in/simulatorResponse' %>
  <%= hidden_field_tag :txn_s2s_flow, '4' %>
  <%= hidden_field_tag :furl, 'https://test-payment-middleware.payu.in/simulatorResponse' %>
  <%= hidden_field_tag :hash, 'e48c5dd4fcde2afebbeac4e34347382d11c93191b8e86b6830102b81f7679b3aa020e472f2b8209d580df5ac0936f96f212e19943b7137a579acf51795dc350e' %>

  <!-- User Input Fields -->
  <div class="form-group">
    <%= label_tag :ccnum, 'Credit Card Number:' %>
    <%= text_field_tag :ccnum, nil, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :ccexpmon, 'Credit Card Expiry Month:' %>
    <%= text_field_tag :ccexpmon, nil, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :ccexpyr, 'Credit Card Expiry Year:' %>
    <%= text_field_tag :ccexpyr, nil, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :ccvv, 'CVV:' %>
    <%= text_field_tag :ccvv, nil, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :ccname, 'Cardholder Name:' %>
    <%= text_field_tag :ccname, nil, class: 'form-control' %>
  </div>

  <!-- Submit Button -->
  <%= submit_tag 'Pay Now', class: 'btn btn-primary' %>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Buy Now", new_payment_path(product_id: @product.id, amount: @product.price) %>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>